import type { TablerIcon } from "@tabler/icons-react"
import {
  IconAdjustmentsSpark,
  IconAiAgent,
  IconAiAgents,
  IconAiGateway,
  IconAlertTriangle,
  IconAlertTriangleFilled,
  IconArchive,
  IconArchiveFilled,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowsSort,
  IconAutomation,
  IconBattery,
  IconBatteryFilled,
  IconBatterySpark,
  IconBell,
  IconBellFilled,
  IconBluetooth,
  IconBodyScan,
  IconBookmark,
  IconBookmarkAi,
  IconBookmarkFilled,
  IconBotId,
  IconBrain,
  IconBriefcase,
  IconBriefcaseFilled,
  IconBulb,
  IconBulbFilled,
  IconCalculator,
  IconCalculatorFilled,
  IconCalendar,
  IconCalendarFilled,
  IconCamera,
  IconCameraAi,
  IconCameraFilled,
  IconChartBar,
  IconChartLine,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircleCheck,
  IconCircleCheckFilled,
  IconCircleX,
  IconCircleXFilled,
  IconClipboard,
  IconClipboardCheck,
  IconClock,
  IconClockFilled,
  IconCloud,
  IconCloudFilled,
  IconCodeAi,
  IconCopy,
  IconCopyFilled,
  IconCpu,
  IconCreditCard,
  IconCube,
  IconCubeSpark,
  IconDatabase,
  IconDatabaseFilled,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDeviceVisionPro,
  IconDeviceVisionProFilled,
  IconDeviceWatch,
  IconDeviceWatchFilled,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconDownloadFilled,
  IconEarScan,
  IconEdit,
  IconEditFilled,
  IconExternalLink,
  IconEye,
  IconEyeFilled,
  IconEyeOff,
  IconEyeSpark,
  IconEyeglass,
  IconEyeglassFilled,
  IconFile,
  IconFileAi,
  IconFileFilled,
  IconFileInvoice,
  IconFileInvoiceFilled,
  IconFileTextAi,
  IconFilter,
  IconFilterFilled,
  IconFlag,
  IconFlagFilled,
  IconFlagSpark,
  IconFolder,
  IconFolderFilled,
  IconHeadphones,
  IconHeadphonesFilled,
  IconHeart,
  IconHeartFilled,
  IconHeartSpark,
  IconHelpCircle,
  IconHelpCircleFilled,
  IconHome,
  IconHomeFilled,
  IconHomeSpark,
  IconImageGeneration,
  IconInfoCircle,
  IconInfoCircleFilled,
  IconInputAi,
  IconLink,
  IconListDetails,
  IconListDetailsFilled,
  IconLoader2,
  IconLock,
  IconLockFilled,
  IconLockOpen,
  IconMail,
  IconMailAi,
  IconMailFilled,
  IconMapPin,
  IconMapPinFilled,
  IconMenu2,
  IconMessage,
  IconMessageChatbot,
  IconMessageChatbotFilled,
  IconMessageFilled,
  IconMessages,
  IconMessagesFilled,
  IconMicrophone,
  IconMicrophoneFilled,
  IconMinus,
  IconNoiseReduction,
  IconObjectScan,
  IconPackage,
  IconPalette,
  IconPaletteFilled,
  IconPaperclip,
  IconPhone,
  IconPhoneSpark,
  IconPhoto,
  IconPhotoAi,
  IconPhotoFilled,
  IconPhotoScan,
  IconPlayerPlay,
  IconPlayerPlayFilled,
  IconPlayerStop,
  IconPlug,
  IconPlus,
  IconPrompt,
  IconReceipt,
  IconReceiptFilled,
  IconRefresh,
  IconRobot,
  IconRocket,
  IconScanCube,
  IconScanTraces,
  IconSearch,
  IconSearchFilled,
  IconSend,
  IconSendFilled,
  IconServerSpark,
  IconSettings,
  IconSettingsAi,
  IconSettingsFilled,
  IconShare,
  IconShield,
  IconShieldCheck,
  IconShieldCheckFilled,
  IconShoppingCart,
  IconSparkles,
  IconSparklesFilled,
  IconStack2,
  IconStack2Filled,
  IconStar,
  IconStarFilled,
  IconStars,
  IconSubtitlesAi,
  IconTableSpark,
  IconTag,
  IconTagFilled,
  IconTextScanAi,
  IconThinkingHigh,
  IconThinkingLow,
  IconThinkingMedium,
  IconThumbDown,
  IconThumbUp,
  IconTools,
  IconTrash,
  IconTrashFilled,
  IconTruck,
  IconUpload,
  IconUser,
  IconUserFilled,
  IconUserPlus,
  IconUserScan,
  IconUsers,
  IconVideo,
  IconVideoFilled,
  IconWand,
  IconWifi,
  IconWorld,
  IconWorldFilled,
  IconX,
  IconZeroConfig,
  IconZoomScan,
  IconZoomScanFilled,
} from "@tabler/icons-react"

export type IconCatalogItem = readonly [
  label: string,
  exportName: string,
  component: TablerIcon,
]

export const basicOutlineIcons: IconCatalogItem[] = [
  ["Chevron Left", "IconChevronLeft", IconChevronLeft],
  ["Chevron Right", "IconChevronRight", IconChevronRight],
  ["Chevron Up", "IconChevronUp", IconChevronUp],
  ["Chevron Down", "IconChevronDown", IconChevronDown],
  ["Arrow Left", "IconArrowLeft", IconArrowLeft],
  ["Arrow Right", "IconArrowRight", IconArrowRight],
  ["Arrow Up", "IconArrowUp", IconArrowUp],
  ["Arrow Down", "IconArrowDown", IconArrowDown],
  ["Menu", "IconMenu2", IconMenu2],
  ["Close", "IconX", IconX],
  ["More Horizontal", "IconDots", IconDots],
  ["More Vertical", "IconDotsVertical", IconDotsVertical],
  ["Add", "IconPlus", IconPlus],
  ["Remove", "IconMinus", IconMinus],
  ["Confirm", "IconCheck", IconCheck],
  ["Search", "IconSearch", IconSearch],
  ["Edit", "IconEdit", IconEdit],
  ["Delete", "IconTrash", IconTrash],
  ["Copy", "IconCopy", IconCopy],
  ["Download", "IconDownload", IconDownload],
  ["Upload", "IconUpload", IconUpload],
  ["Refresh", "IconRefresh", IconRefresh],
  ["Filter", "IconFilter", IconFilter],
  ["Sort", "IconArrowsSort", IconArrowsSort],
  ["External Link", "IconExternalLink", IconExternalLink],
  ["Link", "IconLink", IconLink],
  ["Show", "IconEye", IconEye],
  ["Hide", "IconEyeOff", IconEyeOff],
  ["Success", "IconCircleCheck", IconCircleCheck],
  ["Error", "IconCircleX", IconCircleX],
  ["Warning", "IconAlertTriangle", IconAlertTriangle],
  ["Info", "IconInfoCircle", IconInfoCircle],
  ["Loading", "IconLoader2", IconLoader2],
  ["Help", "IconHelpCircle", IconHelpCircle],
  ["Home", "IconHome", IconHome],
  ["User", "IconUser", IconUser],
  ["Settings", "IconSettings", IconSettings],
  ["Notification", "IconBell", IconBell],
  ["Calendar", "IconCalendar", IconCalendar],
  ["Time", "IconClock", IconClock],
  ["Message", "IconMessage", IconMessage],
  ["Messages", "IconMessages", IconMessages],
  ["Send", "IconSend", IconSend],
  ["Microphone", "IconMicrophone", IconMicrophone],
  ["Mail", "IconMail", IconMail],
  ["File", "IconFile", IconFile],
  ["Folder", "IconFolder", IconFolder],
  ["Cloud", "IconCloud", IconCloud],
  ["Database", "IconDatabase", IconDatabase],
  ["Archive", "IconArchive", IconArchive],
  ["Tag", "IconTag", IconTag],
  ["Bookmark", "IconBookmark", IconBookmark],
  ["Briefcase", "IconBriefcase", IconBriefcase],
  ["Flag", "IconFlag", IconFlag],
  ["Lock", "IconLock", IconLock],
  ["Shield Check", "IconShieldCheck", IconShieldCheck],
  ["Map Pin", "IconMapPin", IconMapPin],
  ["World", "IconWorld", IconWorld],
  ["Star", "IconStar", IconStar],
  ["Heart", "IconHeart", IconHeart],
  ["Phone", "IconPhone", IconPhone],
  ["Paperclip", "IconPaperclip", IconPaperclip],
  ["Share", "IconShare", IconShare],
  ["Users", "IconUsers", IconUsers],
  ["User Plus", "IconUserPlus", IconUserPlus],
  ["Lock Open", "IconLockOpen", IconLockOpen],
  ["Shield", "IconShield", IconShield],
  ["Device Mobile", "IconDeviceMobile", IconDeviceMobile],
  ["Device Desktop", "IconDeviceDesktop", IconDeviceDesktop],
  ["Wifi", "IconWifi", IconWifi],
  ["Bluetooth", "IconBluetooth", IconBluetooth],
  ["Plug", "IconPlug", IconPlug],
  ["Clipboard", "IconClipboard", IconClipboard],
  ["Clipboard Check", "IconClipboardCheck", IconClipboardCheck],
  ["Chart Bar", "IconChartBar", IconChartBar],
  ["Chart Line", "IconChartLine", IconChartLine],
  ["Shopping Cart", "IconShoppingCart", IconShoppingCart],
  ["Credit Card", "IconCreditCard", IconCreditCard],
  ["Truck", "IconTruck", IconTruck],
  ["Tools", "IconTools", IconTools],
  ["Check", "IconCheck", IconCheck],
  ["Thumb Up", "IconThumbUp", IconThumbUp],
  ["Thumb Down", "IconThumbDown", IconThumbDown],
]

export const basicFilledIcons: IconCatalogItem[] = [
  ["Search", "IconSearchFilled", IconSearchFilled],
  ["Edit", "IconEditFilled", IconEditFilled],
  ["Delete", "IconTrashFilled", IconTrashFilled],
  ["Copy", "IconCopyFilled", IconCopyFilled],
  ["Filter", "IconFilterFilled", IconFilterFilled],
  ["Show", "IconEyeFilled", IconEyeFilled],
  ["Success", "IconCircleCheckFilled", IconCircleCheckFilled],
  ["Error", "IconCircleXFilled", IconCircleXFilled],
  ["Warning", "IconAlertTriangleFilled", IconAlertTriangleFilled],
  ["Info", "IconInfoCircleFilled", IconInfoCircleFilled],
  ["Help", "IconHelpCircleFilled", IconHelpCircleFilled],
  ["Home", "IconHomeFilled", IconHomeFilled],
  ["User", "IconUserFilled", IconUserFilled],
  ["Settings", "IconSettingsFilled", IconSettingsFilled],
  ["Notification", "IconBellFilled", IconBellFilled],
  ["Calendar", "IconCalendarFilled", IconCalendarFilled],
  ["Time", "IconClockFilled", IconClockFilled],
  ["Message", "IconMessageFilled", IconMessageFilled],
  ["Messages", "IconMessagesFilled", IconMessagesFilled],
  ["Send", "IconSendFilled", IconSendFilled],
  ["Microphone", "IconMicrophoneFilled", IconMicrophoneFilled],
  ["Mail", "IconMailFilled", IconMailFilled],
  ["File", "IconFileFilled", IconFileFilled],
  ["Folder", "IconFolderFilled", IconFolderFilled],
  ["Cloud", "IconCloudFilled", IconCloudFilled],
  ["Database", "IconDatabaseFilled", IconDatabaseFilled],
  ["Archive", "IconArchiveFilled", IconArchiveFilled],
  ["Tag", "IconTagFilled", IconTagFilled],
  ["Bookmark", "IconBookmarkFilled", IconBookmarkFilled],
  ["Briefcase", "IconBriefcaseFilled", IconBriefcaseFilled],
  ["Flag", "IconFlagFilled", IconFlagFilled],
  ["Lock", "IconLockFilled", IconLockFilled],
  ["Shield Check", "IconShieldCheckFilled", IconShieldCheckFilled],
  ["Map Pin", "IconMapPinFilled", IconMapPinFilled],
  ["World", "IconWorldFilled", IconWorldFilled],
  ["Star", "IconStarFilled", IconStarFilled],
  ["Heart", "IconHeartFilled", IconHeartFilled],
]

export const productOutlineIcons: IconCatalogItem[] = [
  ["Sparkles", "IconSparkles", IconSparkles],
  ["Bulb", "IconBulb", IconBulb],
  ["Wand", "IconWand", IconWand],
  ["Robot", "IconRobot", IconRobot],
  ["Message Chatbot", "IconMessageChatbot", IconMessageChatbot],
  ["Photo", "IconPhoto", IconPhoto],
  ["Cube", "IconCube", IconCube],
  ["Layers", "IconStack2", IconStack2],
  ["Palette", "IconPalette", IconPalette],
  ["Video", "IconVideo", IconVideo],
  ["Player Play", "IconPlayerPlay", IconPlayerPlay],
  ["Player Stop", "IconPlayerStop", IconPlayerStop],
  ["Camera", "IconCamera", IconCamera],
  ["Device Watch", "IconDeviceWatch", IconDeviceWatch],
  ["Glasses", "IconEyeglass", IconEyeglass],
  ["Headphones", "IconHeadphones", IconHeadphones],
  ["Cpu", "IconCpu", IconCpu],
  ["Battery", "IconBattery", IconBattery],
  ["Package", "IconPackage", IconPackage],
  ["List Details", "IconListDetails", IconListDetails],
  ["File Invoice", "IconFileInvoice", IconFileInvoice],
  ["Receipt", "IconReceipt", IconReceipt],
  ["Calculator", "IconCalculator", IconCalculator],
  ["Rocket", "IconRocket", IconRocket],
  ["Download", "IconDownload", IconDownload],
  ["AI Agent", "IconAiAgent", IconAiAgent],
  ["AI Agents", "IconAiAgents", IconAiAgents],
  ["Prompt", "IconPrompt", IconPrompt],
  ["Input AI", "IconInputAi", IconInputAi],
  ["Automation", "IconAutomation", IconAutomation],
  ["Brain", "IconBrain", IconBrain],
  ["Photo AI", "IconPhotoAi", IconPhotoAi],
  ["Camera AI", "IconCameraAi", IconCameraAi],
  ["Cube Spark", "IconCubeSpark", IconCubeSpark],
  ["File AI", "IconFileAi", IconFileAi],
  ["Subtitles AI", "IconSubtitlesAi", IconSubtitlesAi],
  ["Settings AI", "IconSettingsAi", IconSettingsAi],
  ["File Text AI", "IconFileTextAi", IconFileTextAi],
  ["Text Scan AI", "IconTextScanAi", IconTextScanAi],
  ["Scan Cube", "IconScanCube", IconScanCube],
  ["Object Scan", "IconObjectScan", IconObjectScan],
  ["Photo Scan", "IconPhotoScan", IconPhotoScan],
  ["Code AI", "IconCodeAi", IconCodeAi],
  ["AI Gateway", "IconAiGateway", IconAiGateway],
  ["Zoom Scan", "IconZoomScan", IconZoomScan],
  ["Device Vision Pro", "IconDeviceVisionPro", IconDeviceVisionPro],
  ["Image Generation", "IconImageGeneration", IconImageGeneration],
  ["Bot ID", "IconBotId", IconBotId],
  ["Bookmark AI", "IconBookmarkAi", IconBookmarkAi],
  ["Mail AI", "IconMailAi", IconMailAi],
  ["Adjustments Spark", "IconAdjustmentsSpark", IconAdjustmentsSpark],
  ["Eye Spark", "IconEyeSpark", IconEyeSpark],
  ["Server Spark", "IconServerSpark", IconServerSpark],
  ["Table Spark", "IconTableSpark", IconTableSpark],
  ["Body Scan", "IconBodyScan", IconBodyScan],
  ["Ear Scan", "IconEarScan", IconEarScan],
  ["User Scan", "IconUserScan", IconUserScan],
  ["Noise Reduction", "IconNoiseReduction", IconNoiseReduction],
  ["Battery Spark", "IconBatterySpark", IconBatterySpark],
  ["Phone Spark", "IconPhoneSpark", IconPhoneSpark],
  ["Heart Spark", "IconHeartSpark", IconHeartSpark],
  ["Home Spark", "IconHomeSpark", IconHomeSpark],
  ["Flag Spark", "IconFlagSpark", IconFlagSpark],
  ["Scan Traces", "IconScanTraces", IconScanTraces],
  ["Zero Config", "IconZeroConfig", IconZeroConfig],
  ["Thinking Low", "IconThinkingLow", IconThinkingLow],
  ["Thinking Medium", "IconThinkingMedium", IconThinkingMedium],
  ["Thinking High", "IconThinkingHigh", IconThinkingHigh],
  ["Four Star", "IconStars", IconStars],
]

export const productFilledIcons: IconCatalogItem[] = [
  ["Sparkles", "IconSparklesFilled", IconSparklesFilled],
  ["Bulb", "IconBulbFilled", IconBulbFilled],
  ["Message Chatbot", "IconMessageChatbotFilled", IconMessageChatbotFilled],
  ["Photo", "IconPhotoFilled", IconPhotoFilled],
  ["Layers", "IconStack2Filled", IconStack2Filled],
  ["Palette", "IconPaletteFilled", IconPaletteFilled],
  ["Video", "IconVideoFilled", IconVideoFilled],
  ["Player Play", "IconPlayerPlayFilled", IconPlayerPlayFilled],
  ["Camera", "IconCameraFilled", IconCameraFilled],
  ["Device Watch", "IconDeviceWatchFilled", IconDeviceWatchFilled],
  ["Glasses", "IconEyeglassFilled", IconEyeglassFilled],
  ["Headphones", "IconHeadphonesFilled", IconHeadphonesFilled],
  ["Battery", "IconBatteryFilled", IconBatteryFilled],
  ["List Details", "IconListDetailsFilled", IconListDetailsFilled],
  ["File Invoice", "IconFileInvoiceFilled", IconFileInvoiceFilled],
  ["Receipt", "IconReceiptFilled", IconReceiptFilled],
  ["Calculator", "IconCalculatorFilled", IconCalculatorFilled],
  ["Download", "IconDownloadFilled", IconDownloadFilled],
  ["Zoom Scan", "IconZoomScanFilled", IconZoomScanFilled],
  ["Device Vision Pro", "IconDeviceVisionProFilled", IconDeviceVisionProFilled],
]

export const socialIconNames = [
  "facebook",
  "instagram",
  "google",
  "youtube",
  "x",
  "tiktok",
  "tumblr",
] as const
